import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'providers/todo_provider.dart';
import 'providers/person_provider.dart';
import 'providers/auth_provider.dart';
import 'screens/main_screen.dart';
import 'screens/login_screen.dart';
import 'firebase_options.dart'; // This file is generated by FlutterFire CLI
import 'package:tigidou/l10n/app_localizations.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // NOTE: DefaultFirebaseOptions requires running `flutterfire configure`
  // For now, we'll wrap in a try-catch or assume the user has configured it.
  // If firebase_options.dart doesn't exist, this will fail to compile.
  // We will assume the user will run `flutterfire configure`.
  // However, to make it compile initially without that file (if the user hasn't run it yet),
  // we might need to comment it out or handle it.
  // But the prompt implies using Firebase, so we should expect the configuration.

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => TodoProvider()),
        ChangeNotifierProvider(create: (_) => PersonProvider()),
        ChangeNotifierProvider(create: (_) => AuthProvider()),
      ],
      child: Consumer<AuthProvider>(
        builder: (context, auth, _) {
          return MaterialApp(
            onGenerateTitle: (context) =>
                AppLocalizations.of(context)!.appTitle,
            localizationsDelegates: AppLocalizations.localizationsDelegates,
            supportedLocales: AppLocalizations.supportedLocales,
            theme: ThemeData(primarySwatch: Colors.blue),
            home: auth.isAuthenticated
                ? const MainScreen()
                : const LoginScreen(),
          );
        },
      ),
    );
  }
}
